import Head from "next/head"
import NavVar from "../components/NavVar"
import styles from "../styles/Home.module.css"
import Header from "../components/Header"
import LotteryEntrance from "../components/LotteryEntrance"
import { useMoralis } from "react-moralis"
import Link from "next/link"

const supportedChains = ["31337", "4"]

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavVar></NavVar>
      <h1 className="title">
        Read{" "}
        <Link href="/admin">
          <a>this page!</a>
        </Link>
      </h1>
    </div>
  )
}
