import Head from "next/head"
import Hero from "../components/Hero"
import NavBar from "../components/NavBar"
import styles from "../styles/Home.module.css"
import Header from "../components/Header"
import LotteryEntrance from "../components/LotteryEntrance"
import { useMoralis } from "react-moralis"

const supportedChains = ["31337", "4"]

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavBar></NavBar>
      </div>
      <Hero></Hero>
    </div>
  )
}
